CC=gcc
CFLAGS=-W -Wall -ansi -pedantic
LDFLAGS=
EXEC=

all: $(EXEC)

test1: vect.o mat.o test1.o
	$(CC) -o hello hello.o main.o $(LDFLAGS)

vect.o: Vect.cpp
	$(CC) -o vect.o -c Vect.cpp $(CFLAGS)

mat.o: Mat.cpp
	$(CC) -o mat.o -c Mat.cpp $(CFLAGS)

test1.o: test1.c Mat.h Vect.h
	$(CC) -o test1.o -c test1.cpp $(CFLAGS)

clean:
	rm -rf *.o

mrproper: clean
	rm -rf $(EXEC)